CloudFlare:
  mail: yumusb@foxmail.com
  token: yourtoken
#将要监控的域名记录
domain:
  name: yourdomain.com
  zone:
  - subdomain: 'www'
    type: http
    port: 80
#主用加备用记录 都写在这里
records:
- content: yumusb.coding.me 
  name: 'www'
  type: CNAME
  proxied: false
- content: yumusb.github.io
  name: 'www'
  type: CNAME
  proxied: false