CloudFlare:
  mail: 110539hang@gmail.com
  token: 
#将要监控的域名记录
domain:
  name: yinhecdn.xyz
  zone:
  - subdomain: 'www'
    type: http
    port: 80
#主用加备用记录 都写在这里
records:
- content: hk.yinhecdn.xyz 
  name: 'www'
  type: CNAME
  proxied: false
- content: us.yinhecdn.xyz
  name: 'www'
  type: CNAME
  proxied: false
